// Central SEO configuration
export const siteConfig = {
  name: "NAITEC Digital",
  url: "https://naitec.com.au",
  ogImage: "/images/pages/page-header.jpg",
  description:
    "Based in Newcastle NSW, NAITEC Digital helps businesses design, build, and improve the digital systems they rely on every day. Specialists in React, Angular, Drupal, AI & intelligent automation.",
  locale: "en_AU",
  type: "website" as const,
  creator: "NAITEC Digital",
  abn: "88 611 039 466",
  email: "contact@naitec.com.au",
  phone: "",
  address: {
    streetAddress: "Level 2, 384 Hunter Street",
    postalAddress: "PO Box 1069",
    addressLocality: "Newcastle",
    addressRegion: "NSW",
    postalCode: "2300",
    addressCountry: "AU",
  },
  social: {
    linkedin: "https://www.linkedin.com/company/naitec-digital",
  },
  keywords: [
    "digital solutions Newcastle",
    "web development Australia",
    "React development",
    "Angular development",
    "Drupal development",
    "GovCMS",
    "AI automation",
    "workflow automation",
    "digital transformation",
    "SEO services",
    "UX design",
    "government digital services",
    "BuyICT supplier",
    "Newcastle web agency",
    "Next.js development",
    "cloud DevOps",
    "data analytics",
    "custom software development",
  ],
};
